version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/kanjivg"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/flutter_kanjivg"
    schedule:
      interval: "weekly"
