name: kanjivg
description: Dart implementation of a parser for resources from the Kanji Vector Graphics project.
version: 0.1.1
repository: https://github.com/n-bernat/kanjivg
issue_tracker: https://github.com/n-bernat/kanjivg/issues

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  xml: ^6.3.0

dev_dependencies:
  leancode_lint: ^14.2.0
  test: ^1.25.0
