name: kanjivg
description: Dart implementation of a parser for resources from the Kanji Vector Graphics project.
version: 0.0.1
repository: https://github.com/n-bernat/kanjivg
issue_tracker: https://github.com/n-bernat/kanjivg/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  test: ^1.24.9
