name: flutter_kanjivg
description: Flutter widgets that simplify displaying data from the Kanji Vector Graphics project. Built on the top of `kanjivg` package.
version: 0.0.1
repository: https://github.com/n-bernat/kanjivg
issue_tracker: https://github.com/n-bernat/kanjivg/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  kanjivg: ^0.0.1
  vector_graphics_compiler: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
