name: flutter_kanjivg
description: Flutter widgets that simplify displaying data from the Kanji Vector Graphics project. Built on the top of `kanjivg` package.
version: 0.0.1
repository: https://github.com/n-bernat/kanjivg
issue_tracker: https://github.com/n-bernat/kanjivg/issues

# Temporary until `kanjivg` package is published
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  kanjivg:
    path: ../kanjivg

dev_dependencies:
  flutter_test:
    sdk: flutter
