name: flutter_kanjivg
description: Flutter widgets that simplify displaying data from the Kanji Vector Graphics project. Built on the top of `kanjivg` package.
version: 0.1.0
repository: https://github.com/n-bernat/kanjivg
issue_tracker: https://github.com/n-bernat/kanjivg/issues
documentation: https://kanjivg.tagaini.net/index.html
screenshots:
  - description: Preview of the animated character.
    path: screenshots/screenshot.webp

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  kanjivg: ^0.1.0
  vector_graphics_compiler: ^1.1.6

dev_dependencies:
  leancode_lint: ">=13.0.0 <15.0.0"
  test: ^1.24.9
