name: kanjivg - Checks
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "kanjivg/**"
  push:
    paths:
      - "kanjivg/**"
    branches:
      - master

jobs:
  build:
    timeout-minutes: 5
    name: Dart checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./kanjivg"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Print version
        run: dart --version

      - name: Get dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format . --set-exit-if-changed

      - name: Run analyzer
        run: dart analyze

      - name: Run tests
        run: dart test --coverage=coverage

      - name: Generate .lcov file
        run: |
          dart pub global activate coverage
          format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib

      - name: Upload coverage
        run: curl -s https://codecov.io/bash | bash
