name: flutter_kanjivg - Checks
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  pull_request:
    paths:
      - "flutter_kanjivg/**"
  push:
    paths:
      - "flutter_kanjivg/**"
    branches:
      - master

jobs:
  build:
    timeout-minutes: 5
    name: Flutter checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./flutter_kanjivg"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"

      - name: Print version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format . --set-exit-if-changed

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage .

      - name: Generate .lcov file
        run: |
          dart pub global activate coverage
          format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib

      - name: Upload coverage
        run: curl -s https://codecov.io/bash | bash
