name: flutter_kanjivg - Checks
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "flutter_kanjivg/**"
  push:
    paths:
      - "flutter_kanjivg/**"
    branches:
      - master

jobs:
  build:
    timeout-minutes: 5
    name: Flutter checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./flutter_kanjivg"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: "stable"

      - name: Print version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format . --set-exit-if-changed

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: ./test/flutter_kanjivg_test.dart.vm.json
