name: Tag packages
on:
  push:
    branches:
      - master
    paths:
      - kanjivg/CHANGELOG.md
      - flutter_kanjivg/CHANGELOG.md

jobs:
  publish:
    name: Tag packages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Test packages
        uses: n-bernat/flutter-tools/packages/test@master
        with:
          custom-lint: true

      - name: Tag packages
        uses: n-bernat/flutter-tools/packages/tag@master
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
